ProjectManagementSystem/ProjectManagementSystem/Models/Requirement.cs
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ProjectManagementSystem.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Requirement
    {
        public Requirement()
        {
            this.Hours = new HashSet<Hour>();
        }
    
        public int RequirementID { get; set; }
        public int ProjectID { get; set; }
        public string RequirementType { get; set; }
        public string Description { get; set; }
        public string Number { get; set; }
    
        public virtual Project Project { get; set; }
        public virtual ICollection<Hour> Hours { get; set; }
    }
}

ProjectManagementSystem/ProjectManagementSystem/Controllers/RequirementsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectManagementSystem.Models;

namespace ProjectManagementSystem.Controllers
{
    public class RequirementsController : Controller
    {
        private dbProjectMSEntities projectDb = new dbProjectMSEntities();

        // GET: Requirements
        public ActionResult Index(int id)
        {
            var resultRequirements = from req in projectDb.Requirements where req.ProjectID == id orderby req.Number ascending select req;
            ViewBag.ProjectId = id;
            return View(resultRequirements.ToList());
        }

        [HttpGet]
        public ActionResult Create(int id) {
            ViewBag.ProjectId = id;
            return View();
        }

        [HttpPost]
        public ActionResult Create(int id, string requirementNumber, string requirementDescription, string requirementType) {
            Requirement req = new Requirement() {
                ProjectID = id,
                Number = requirementNumber,
                Description = requirementDescription,
                RequirementType = requirementType
            };
            projectDb.Requirements.Add(req);
            projectDb.SaveChanges();

            ViewBag.ProjectId = id;
            return RedirectToAction("Index", new { id = id });
        }

        [HttpGet]
        public ActionResult Edit(int id) {
            var resultRequirement = from r in projectDb.Requirements where r.RequirementID == id select r;
            Requirement req = resultRequirement.Single();

            ViewBag.ProjectId = req.ProjectID;
            return View(req);
        }

        [HttpPost]
        public ActionResult Edit(int id, string requirementNumber, string requirementDescription, string requirementType) {
            var resultRequirement = from r in projectDb.Requirements where r.RequirementID == id select r;
            Requirement req = resultRequirement.Single();
            req.Number = requirementNumber;
            req.Description = requirementDescription;
            req.RequirementType = requirementType;
            projectDb.SaveChanges();

            return RedirectToAction("Index", new { id = req.ProjectID });
        }

        [HttpPost]
        public ActionResult Delete(int deleteRequirement) {
            var resultRequirement = from r in projectDb.Requirements where r.RequirementID == deleteRequirement select r;
            Requirement req = resultRequirement.Single();
            projectDb.Requirements.Remove(req);
            projectDb.SaveChanges();

            return RedirectToAction("Index", new { id = req.ProjectID });
        }
    }
}

ProjectManagementSystem/ProjectManagementSystem/Views/Requirements/Create.cshtml
@{
    ViewBag.Title = "Create a Requirement";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
}

@section SectionNav {
    @Html.Partial("_RequirementsNavbar")
}

@using(Html.BeginForm("Create", "Requirements", new { id = ViewBag.ProjectId }, FormMethod.Post, new { @class = "form-horizontal" })) {
    <h3>Create a Requirement</h3>
    <div class="form-group">
        <label for="RequirementNumber" class="col-sm-2 control-label">Number:</label>
        <div class="col-sm-1">
            <input type="text" class="form-control" name="RequirementNumber" id="RequirementNumber" />
        </div>
    </div>
    <div class="form-group">
        <label for="RequirementDescription" class="control-label col-sm-2">Requirement:</label>
        <div class="col-sm-8">
            <textarea class="form-control" id="RequirementDescription" name="RequirementDescription" rows="8"></textarea>
        </div>
    </div>
    <div class="col-sm-offset-2">
        <div class="radio">
            <label>
                @Html.RadioButton("RequirementType", "Functional", true, null)
                Functional Requirement
            </label>
        </div>
        <div class="radio">
            <label>
                @Html.RadioButton("RequirementType", "Nonunctional", false, null)
                Nonfunctional Requirement
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2 col-sm-offset-1">
            <button type="submit" class="form-control" name="SubmitAdd">Create</button>
        </div>
    </div>
}

ProjectManagementSystem/ProjectManagementSystem/Views/Requirements/Edit.cshtml
@using ProjectManagementSystem.Models
@model Requirement

@{
    ViewBag.Title = "Edit a Requirement";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
}

@section SectionNav {
    @Html.Partial("_RequirementsNavbar")
}

<h2>Edit a Requirement</h2>
@using (Html.BeginForm("Edit", "Requirements", new { id = Model.RequirementID }, FormMethod.Post, new { @class = "form-horizontal" })) {
    <div class="form-group">
        <label for="RequirementNumber" class="col-sm-2 control-label">Number:</label>
        <div class="col-sm-1">
            <input type="text" class="form-control" name="RequirementNumber" id="RequirementNumber" value=@Model.Number />
        </div>
    </div>
    <div class="form-group">
        <label for="RequirementDescription" class="control-label col-sm-2">Description:</label>
        <div class="col-sm-8">
            <textarea class="form-control" id="RequirementDescription" name="RequirementDescription" rows="8">@Model.Description</textarea>
        </div>
    </div>
    <div class="col-sm-offset-2">
        <div class="radio">
            <label>
                @Html.RadioButton("RequirementType", "Functional", Model.RequirementType.Equals("Functional"), null)
                Functional Requirement
            </label>
        </div>
        <div class="radio">
            <label>
                @Html.RadioButton("RequirementType", "Nonunctional", Model.RequirementType.Equals("Nonfunctional"), null)
                Nonfunctional Requirement
            </label>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2 col-sm-offset-1">
            <button type="submit" class="form-control" name="SubmitAdd">Save</button>
        </div>
    </div>
}

ProjectManagementSystem/ProjectManagementSystem/Views/Requirements/Index.cshtml
@using ProjectManagementSystem.Models
@model IEnumerable<Requirement>

@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_ProjectLayout.cshtml";
}

@section SectionNav {
    @Html.Partial("_RequirementsNavbar")
}

<h2>View Requirements</h2>
<div class="container">
@foreach (Requirement req in Model) {
    <div class="row">
        <div class="col-md-1">@req.Number</div>
        <div class="col-md-1">@req.RequirementType</div>
        <div class="col-md-8">@req.Description</div>
        <div class="col-md-2">@Html.ActionLink("Edit", "Edit", "Requirements", new { id = req.RequirementID }, null)</div>
    </div>
}
</div>
<hr />
<h3>Delete a Requirement</h3>
@using (Html.BeginForm("Delete", "Requirements", null, FormMethod.Post, new { @class = "form-horizontal" })) {
    <div class="form-group">
<<<<<<< HEAD
        <label for="DeleteRequirement" class="col-sm-2 control-label">Requirement:</label>
=======
        <label for="DeleteRequirement" class="col-sm-2 control-label">Requirement Number:</label>
>>>>>>> origin/master
        <div class="col-sm-4">
            <select class="form-control" id="DeleteRequirement" name="DeleteRequirement">
                @foreach (Requirement req in Model) {
                    <option value=@Convert.ToString(req.RequirementID)>@req.Number</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2 col-sm-offset-1">
            <button type="submit" class="form-control" name="SubmitDelete">Delete</button>
        </div>
    </div>
}