ProjectManagementSystem/ProjectManagementSystem/Controllers/TimeController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using ProjectManagementSystem.Models;

namespace ProjectManagementSystem.Controllers
{
    [Authorize]
    public class TimeController : Controller
    {
        private dbProjectMSEntities projectDb = new dbProjectMSEntities();

        // GET: Time
        public ActionResult Index(int id)
        {
            var reqsResult = from req in projectDb.Requirements where req.ProjectID == id select req;
            var phasesResult = from phase in projectDb.Phases select phase;
            ViewBag.ProjectId = id;
            return View(new TimeCreateModel {Requirements = reqsResult.ToList(), Phases = phasesResult.ToList()});
        }

        [HttpPost]
        public ActionResult LogTime(int id, int phaseId, int requirementId, float hours) {
            Hour time = new Hour() {
                PhaseID = phaseId,
                RequirementID = requirementId,
                Hours = hours
            };
            projectDb.Hours.Add(time);
            projectDb.SaveChanges();

            return RedirectToAction("Index", new { id = id });
        }

        [HttpGet]
        public ActionResult TimeTotals(int id)
        {
            var timesResult = from t in projectDb.Hours where t.Requirement.ProjectID == id select t;
            List<Hour> times = timesResult.ToList();
            
            ViewBag.ProjectId = id;
            return View(times);
        }
    }
}

ProjectManagementSystem/ProjectManagementSystem/Views/Time/TimeTotals.cshtml
@using ProjectManagementSystem.Models
@model List<Hour>
@{
    Layout = "~/Views/Shared/_Projectlayout.cshtml";

    ViewBag.Title = "Time Totals";
}

@section SectionNav {
    @Html.Partial("_TimeNavbar");
}

@{
    var queryModel = Model.AsQueryable();
    List<Phase> phases = queryModel.Select<Hour, Phase>(time => time.Phase).Distinct().OrderBy(phase => phase.PhaseID).ToList();
    List<Requirement> reqs = queryModel.Select<Hour, Requirement>(time => time.Requirement).Distinct().OrderBy(req => req.RequirementID).ToList();
}

<div class="container">
    <table class="table">
        <tr>
            <th rowspan="2">Requirement</th>
            <th colspan=@phases.Count>Phase</th>
        </tr>
        <tr>
            @foreach (Phase phase in phases) {
                <th>@phase.PhaseName</th>
            }
        </tr>

        @foreach (Requirement req in reqs) {
            <tr>
                <td>@req.Number</td>

                @foreach (Phase phase in phases) {
                    var timeResults = from time in queryModel where time.RequirementID == req.RequirementID && time.PhaseID == phase.PhaseID select time;
                    float total = (float) timeResults.Sum(time => time.Hours);
                    <td>@string.Format("{0:F1}", total)</td>
                }
            </tr>
        }
    </table>
</div>

ProjectManagementSystem/ProjectManagementSystem/Views/Time/index.cshtml
@using ProjectManagementSystem.Models
@model TimeCreateModel

@{
    Layout = "~/Views/Shared/_Projectlayout.cshtml";
    ViewBag.Title = "Time Log";
}

@section SectionNav {
    @Html.Partial("_TimeNavbar");
}

@using (Html.BeginForm("LogTime", "Time", new { id = ViewBag.ProjectId }, FormMethod.Post, new { @class = "form-horizontal" })) {
    <h3>Log Time</h3>
    <div class="form-group">
        <label for="RequirementNumber" class="col-sm-2 control-label"> Requirement Number:</label>
        <div class="col-sm-1">
            <select class="form-control" id="RequirementNumber" name="RequirementId">
                @foreach (Requirement req in Model.Requirements) {
                    <option value=@req.RequirementID>@req.Number</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="Phase" class="col-sm-2 control-label">Phase:</label>
        <div class="col-sm-2">
            <select class="form-control" id="Phase" name="PhaseId">
                @foreach (Phase phase in Model.Phases) {
                    <option value=@phase.PhaseID>@phase.PhaseName</option>
                }
            </select>
        </div>
    </div>
    <div class="form-group">
        <label for="Hours" class="control-label col-sm-2">Hours:</label>
        <div class="col-sm-1">
            <input type="text" id="Hours" name="Hours" placeholder="0" class="form-control" />
        </div>
    </div>
    <div class="form-group">
        <div class="col-sm-2 col-sm-offset-1">
            <button type="submit" class="form-control" name="SubmitAdd">Log</button>
        </div>
    </div>
}